image:
  file: .gitpod.Dockerfile
ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: composer update
    command: php -S localhost:8000 -t src src/index.php

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
